import {
  AlertTriangle,
  Bell,
  CheckCircle,
  Clock3,
  MapPin,
  ShieldAlert,
} from "lucide-react";

const alerts = [
  {
    id: 1,
    location: "Aizawl",
    district: "Aizawl District",
    probability: 99.78,
    level: "Very High",
    status: "Active",
    time: "12 minutes ago",
    message:
      "Very high landslide probability detected due to heavy rainfall, steep slope and elevated soil moisture.",
  },
  {
    id: 2,
    location: "Kolasib",
    district: "Kolasib District",
    probability: 78.42,
    level: "Very High",
    status: "Active",
    time: "28 minutes ago",
    message:
      "Environmental conditions indicate significant landslide potential. Immediate monitoring recommended.",
  },
  {
    id: 3,
    location: "Champhai",
    district: "Champhai District",
    probability: 61.35,
    level: "High",
    status: "Monitoring",
    time: "45 minutes ago",
    message:
      "Increased rainfall and slope conditions have raised the predicted landslide risk.",
  },
  {
    id: 4,
    location: "Serchhip",
    district: "Serchhip District",
    probability: 42.18,
    level: "Moderate",
    status: "Monitoring",
    time: "1 hour ago",
    message:
      "Moderate risk detected. Continue monitoring rainfall and soil moisture conditions.",
  },
  {
    id: 5,
    location: "Lunglei",
    district: "Lunglei District",
    probability: 18.64,
    level: "Low",
    status: "Resolved",
    time: "2 hours ago",
    message:
      "Current environmental conditions indicate relatively low landslide potential.",
  },
];

function AlertsPage() {
  const activeAlerts = alerts.filter(
    (alert) => alert.status === "Active",
  ).length;

  const highRisk = alerts.filter(
    (alert) => alert.level === "High" || alert.level === "Very High",
  ).length;

  const monitoring = alerts.filter(
    (alert) => alert.status === "Monitoring",
  ).length;

  return (
    <div className="min-h-screen bg-[#07110e] px-4 py-8 text-[#e8edf2] sm:px-6 lg:px-8">
      <main className="mx-auto max-w-350">
        {/* HEADER */}
        <div className="mb-8">
          <div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[2px] text-[#91b66e]">
            <Bell size={15} />
            Early Warning System
          </div>

          <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
            <div>
              <h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">
                Risk Alerts
              </h1>

              <p className="mt-2 max-w-2xl text-sm leading-6 text-[#7f918a]">
                Monitor AI-generated landslide warnings and environmental risk
                notifications across monitored locations.
              </p>
            </div>

            <div className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/3 px-3 py-2 text-xs text-[#899790]">
              <span className="h-2 w-2 animate-pulse rounded-full bg-[#b8e986]" />
              Live monitoring
            </div>
          </div>
        </div>

        {/* SUMMARY */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <SummaryCard
            icon={<Bell size={20} />}
            title="Active Alerts"
            value={activeAlerts}
            subtitle="Require attention"
          />

          <SummaryCard
            icon={<ShieldAlert size={20} />}
            title="High Risk"
            value={highRisk}
            subtitle="High + Very High"
          />

          <SummaryCard
            icon={<Clock3 size={20} />}
            title="Monitoring"
            value={monitoring}
            subtitle="Being observed"
          />

          <SummaryCard
            icon={<CheckCircle size={20} />}
            title="Resolved"
            value={alerts.filter((alert) => alert.status === "Resolved").length}
            subtitle="No longer active"
          />
        </div>

        {/* ALERT LIST */}
        <section className="mt-6 rounded-2xl border border-white/[0.07] bg-white/2.5 p-5 sm:p-6">
          <div className="mb-6 flex flex-col gap-3 border-b border-white/[0.07] pb-5 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="font-display text-lg font-bold">
                Recent Risk Notifications
              </h2>

              <p className="mt-1 text-xs text-[#71817a]">
                Latest predictions generated by the AI risk model.
              </p>
            </div>

            <select className="rounded-lg border border-white/10 bg-[#091712] px-3 py-2 text-xs text-[#9ba8a3] outline-none focus:border-[#b8e986]/40">
              <option>All Alerts</option>
              <option>Very High</option>
              <option>High</option>
              <option>Moderate</option>
              <option>Low</option>
            </select>
          </div>

          <div className="space-y-3">
            {alerts.map((alert) => (
              <AlertCard key={alert.id} alert={alert} />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}

function SummaryCard({ icon, title, value, subtitle }) {
  return (
    <div className="rounded-2xl border border-white/[0.07] bg-white/2.5 p-5">
      <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#b8e986]/10 text-[#b8e986]">
        {icon}
      </div>

      <p className="mt-5 text-xs text-[#71817a]">{title}</p>

      <p className="mt-1 font-display text-2xl font-bold">{value}</p>

      <p className="mt-1 text-[11px] text-[#596761]">{subtitle}</p>
    </div>
  );
}

function AlertCard({ alert }) {
  const veryHigh = alert.level === "Very High";
  const high = alert.level === "High";
  const moderate = alert.level === "Moderate";

  let colorClasses = "bg-[#b8e986]/10 text-[#b8e986]";

  if (veryHigh) {
    colorClasses = "bg-red-500/10 text-red-400";
  } else if (high) {
    colorClasses = "bg-orange-500/10 text-orange-400";
  } else if (moderate) {
    colorClasses = "bg-yellow-500/10 text-yellow-400";
  }

  return (
    <article className="rounded-xl border border-white/6 bg-black/10 p-4 transition hover:border-white/12 sm:p-5">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
        {/* LOCATION */}
        <div className="flex gap-4">
          <div
            className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${colorClasses}`}
          >
            <AlertTriangle size={20} />
          </div>

          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h3 className="font-semibold">{alert.location}</h3>

              <span
                className={`rounded-full px-2 py-1 text-[10px] font-bold ${colorClasses}`}
              >
                {alert.level}
              </span>

              <span className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-[#899790]">
                {alert.status}
              </span>
            </div>

            <div className="mt-2 flex flex-wrap gap-4 text-[11px] text-[#687770]">
              <span className="flex items-center gap-1">
                <MapPin size={12} />
                {alert.district}
              </span>

              <span className="flex items-center gap-1">
                <Clock3 size={12} />
                {alert.time}
              </span>
            </div>

            <p className="mt-3 max-w-3xl text-xs leading-5 text-[#7e8d87]">
              {alert.message}
            </p>
          </div>
        </div>

        {/* PROBABILITY */}
        <div className="flex shrink-0 items-center gap-6 border-t border-white/6 pt-4 lg:border-t-0 lg:pt-0">
          <div>
            <p className="text-[10px] uppercase tracking-wider text-[#596761]">
              Probability
            </p>

            <p className="mt-1 font-display text-xl font-bold">
              {alert.probability.toFixed(2)}%
            </p>
          </div>

          <div className="h-10 w-px bg-white/10" />

          <button className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-[#9aa7a1] transition hover:border-[#b8e986]/30 hover:text-[#b8e986]">
            View Details
          </button>
        </div>
      </div>
    </article>
  );
}

export default AlertsPage;
